/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "state-oh.v:1" *)
module state(a, b, floor, clk, rst);
  (* src = "state-oh.v:7" *)
  (* unused_bits = "0" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "state-oh.v:7" *)
  wire _08_;
  (* src = "state-oh.v:7" *)
  wire _09_;
  (* src = "state-oh.v:2" *)
  wire _10_;
  (* src = "state-oh.v:2" *)
  wire _11_;
  (* src = "state-oh.v:3" *)
  wire _12_;
  (* src = "state-oh.v:3" *)
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "state-oh.v:4" *)
  wire _23_;
  (* src = "state-oh.v:5" *)
  wire _24_;
  (* src = "state-oh.v:5" *)
  wire _25_;
  (* src = "state-oh.v:2" *)
  input a;
  (* src = "state-oh.v:2" *)
  input b;
  (* src = "state-oh.v:4" *)
  input clk;
  (* src = "state-oh.v:3" *)
  output [1:0] floor;
  (* src = "state-oh.v:4" *)
  input rst;
  (* src = "state-oh.v:5" *)
  (* unused_bits = "0" *)
  wire [2:0] s;
  INVX1 _26_ (
    .A(_25_),
    .Y(_14_)
  );
  INVX1 _27_ (
    .A(_10_),
    .Y(_15_)
  );
  INVX1 _28_ (
    .A(_23_),
    .Y(_16_)
  );
  NOR2X1 _29_ (
    .A(_24_),
    .B(_25_),
    .Y(_17_)
  );
  INVX1 _30_ (
    .A(_17_),
    .Y(_13_)
  );
  NOR2X1 _31_ (
    .A(_11_),
    .B(_15_),
    .Y(_18_)
  );
  NAND2X1 _32_ (
    .A(_11_),
    .B(_15_),
    .Y(_19_)
  );
  OAI21X1 _33_ (
    .A(_25_),
    .B(_19_),
    .C(_16_),
    .Y(_20_)
  );
  MUX2X1 _34_ (
    .A(_17_),
    .B(_24_),
    .S(_18_),
    .Y(_21_)
  );
  AOI21X1 _35_ (
    .A(_19_),
    .B(_21_),
    .C(_20_),
    .Y(_08_)
  );
  AOI22X1 _36_ (
    .A(_24_),
    .B(_18_),
    .C(_19_),
    .D(_25_),
    .Y(_22_)
  );
  NOR2X1 _37_ (
    .A(_23_),
    .B(_22_),
    .Y(_09_)
  );
  NAND2X1 _38_ (
    .A(_24_),
    .B(_14_),
    .Y(_12_)
  );
  (* src = "state-oh.v:7" *)
  DFFPOSX1 _39_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(s[1])
  );
  (* src = "state-oh.v:7" *)
  DFFPOSX1 _40_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(s[2])
  );
  assign _24_ = s[1];
  assign _25_ = s[2];
  assign floor[1] = _13_;
  assign _11_ = b;
  assign _10_ = a;
  assign _23_ = rst;
  assign _00_[1] = _08_;
  assign _00_[2] = _09_;
  assign floor[0] = _12_;
endmodule
