/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "sel.v:1" *)
module sel(ia, ib, sel, out);
  (* src = "sel.v:2" *)
  input ia;
  (* src = "sel.v:2" *)
  input ib;
  (* src = "sel.v:3" *)
  output out;
  (* src = "sel.v:2" *)
  input sel;
  assign out = sel ? ia : ib;
endmodule
